package dev.ng5m.world.particle

import dev.ng5m.registry.Registries
import dev.ng5m.registry.ResourceKey
import dev.ng5m.serialization.Codec
import dev.ng5m.world.particle.ParticleOptions.Empty
import net.kyori.adventure.key.Key

object ParticleTypes {

    val ANGRY_VILLAGER = register("angry_villager")
    val BLOCK = register("block", ParticleOptions.Block.CODEC)
    val BLOCK_MARKER = register("block_marker", ParticleOptions.Block.CODEC)
    val BUBBLE = register("bubble")
    val CLOUD = register("cloud")
    val CRIT = register("crit")
    val DAMAGE_INDICATOR = register("damage_indicator")
    val DRAGON_BREATH = register("dragon_breath")
    val DRIPPING_LAVA = register("dripping_lava")
    val FALLING_LAVA = register("falling_lava")
    val LANDING_LAVA = register("landing_lava")
    val DRIPPING_WATER = register("dripping_water")
    val FALLING_WATER = register("falling_water")
    val DUST = register("dust", ParticleOptions.Dust.CODEC)
    val DUST_COLOR_TRANSITION = register("dust_color_transition", ParticleOptions.DustColorTransition.CODEC)
    val EFFECT = register("effect")
    val ELDER_GUARDIAN = register("elder_guardian")
    val ENCHANTED_HIT = register("enchanted_hit")
    val ENCHANT = register("enchant")
    val END_ROD = register("end_rod")
    val ENTITY_EFFECT = register("entity_effect", ParticleOptions.Color.CODEC)
    val EXPLOSION_EMITTER = register("explosion_emitter")
    val EXPLOSION = register("explosion")
    val GUST = register("gust")
    val SMALL_GUST = register("small_gust")
    val GUST_EMITTER_LARGE = register("gust_emitter_large")
    val GUST_EMITTER_SMALL = register("gust_emitter_small")
    val SONIC_BOOM = register("sonic_boom")
    val FALLING_DUST = register("falling_dust", ParticleOptions.Block.CODEC)
    val FIREWORK = register("firework")
    val FISHING = register("fishing")
    val FLAME = register("flame")
    val INFESTED = register("infested")
    val CHERRY_LEAVES = register("cherry_leaves")
    val SCULK_SOUL = register("sculk_soul")
    val SCULK_CHARGE = register("sculk_charge", ParticleOptions.Roll.CODEC)
    val SCULK_CHARGE_POP = register("sculk_charge_pop")
    val SOUL_FIRE_FLAME = register("soul_fire_flame")
    val SOUL = register("soul")
    val FLASH = register("flash")
    val HAPPY_VILLAGER = register("happy_villager")
    val COMPOSTER = register("composter")
    val HEART = register("heart")
    val INSTANT_EFFECT = register("instant_effect")
    val ITEM = register("item", ParticleOptions.Item.CODEC)
    val VIBRATION = register("vibration", ParticleOptions.Vibration.CODEC)
    val ITEM_SLIME = register("item_slime")
    val ITEM_COBWEB = register("item_cobweb")
    val ITEM_SNOWBALL = register("item_snowball")
    val LARGE_SMOKE = register("large_smoke")
    val LAVA = register("lava")
    val MYCELIUM = register("mycelium")
    val NOTE = register("note")
    val POOF = register("poof")
    val PORTAL = register("portal")
    val RAIN = register("rain")
    val SMOKE = register("smoke")
    val WHITE_SMOKE = register("white_smoke")
    val SNEEZE = register("sneeze")
    val SPIT = register("spit")
    val SQUID_INK = register("squid_ink")
    val SWEEP_ATTACK = register("sweep_attack")
    val TOTEM_OF_UNDYING = register("totem_of_undying")
    val UNDERWATER = register("underwater")
    val SPLASH = register("splash")
    val WITCH = register("witch")
    val BUBBLE_POP = register("bubble_pop")
    val CURRENT_DOWN = register("current_down")
    val BUBBLE_COLUMN_UP = register("bubble_column_up")
    val NAUTILUS = register("nautilus")
    val DOLPHIN = register("dolphin")
    val CAMPFIRE_COSY_SMOKE = register("campfire_cosy_smoke")
    val CAMPFIRE_SIGNAL_SMOKE = register("campfire_signal_smoke")
    val DRIPPING_HONEY = register("dripping_honey")
    val FALLING_HONEY = register("falling_honey")
    val LANDING_HONEY = register("landing_honey")
    val FALLING_NECTAR = register("falling_nectar")
    val FALLING_SPORE_BLOSSOM = register("falling_spore_blossom")
    val ASH = register("ash")
    val CRIMSON_SPORE = register("crimson_spore")
    val WARPED_SPORE = register("warped_spore")
    val SPORE_BLOSSOM_AIR = register("spore_blossom_air")
    val DRIPPING_OBSIDIAN_TEAR = register("dripping_obsidian_tear")
    val FALLING_OBSIDIAN_TEAR = register("falling_obsidian_tear")
    val LANDING_OBSIDIAN_TEAR = register("landing_obsidian_tear")
    val REVERSE_PORTAL = register("reverse_portal")
    val WHITE_ASH = register("white_ash")
    val SMALL_FLAME = register("small_flame")
    val SNOWFLAKE = register("snowflake")
    val DRIPPING_DRIPSTONE_LAVA = register("dripping_dripstone_lava")
    val FALLING_DRIPSTONE_LAVA = register("falling_dripstone_lava")
    val DRIPPING_DRIPSTONE_WATER = register("dripping_dripstone_water")
    val FALLING_DRIPSTONE_WATER = register("falling_dripstone_water")
    val GLOW_SQUID_INK = register("glow_squid_ink")
    val GLOW = register("glow")
    val WAX_ON = register("wax_on")
    val WAX_OFF = register("wax_off")
    val ELECTRIC_SPARK = register("electric_spark")
    val SCRAPE = register("scrape")
    val SHRIEK = register("shriek", ParticleOptions.Delay.CODEC)
    val EGG_CRACK = register("egg_crack")
    val DUST_PLUME = register("dust_plume")
    val TRIAL_SPAWNER_DETECTION = register("trial_spawner_detection")
    val TRIAL_SPAWNER_DETECTION_OMINOUS = register("trial_spawner_detection_ominous")
    val VAULT_CONNECTION = register("vault_connection")
    val DUST_PILLAR = register("dust_pillar", ParticleOptions.Block.CODEC)
    val OMINOUS_SPAWNING = register("ominous_spawning")
    val RAID_OMEN = register("raid_omen")
    val TRIAL_OMEN = register("trial_omen")

    @Suppress("UNCHECKED_CAST")
    private fun <O : ParticleOptions> register(id: String, optionsCodec: Codec<O>): ResourceKey<ParticleType<O>> {
        val key = Key.key(id)
        return Registries.PARTICLE_TYPE.register(key, ParticleType(key, optionsCodec)) as ResourceKey<ParticleType<O>>
    }

    private fun register(id: String): ResourceKey<ParticleType<ParticleOptions.Empty>> {
        return register(id, Empty.CODEC)
    }

}